//! C/C++ header generator for embedded-audio projects.

use crate::project::DawProject;

/// Generates a C/C++ header (.h) with song arrays and structs.
pub fn generate_c_header(project: &DawProject) -> String {
    let mut code = String::new();
    code.push_str("/* Auto-generated by embedded-audio DAW studio */\n");
    code.push_str("#pragma once\n\n");
    code.push_str("#include <stdint.h>\n");
    code.push_str("#include <stdbool.h>\n\n");

    code.push_str(&format!("#define SONG_TITLE \"{}\"\n", project.title));
    code.push_str(&format!("#define SONG_BPM {}\n", project.bpm));
    code.push_str(&format!(
        "#define SAMPLE_RATE_HZ {}\n",
        project.sample_rate_hz
    ));
    code.push_str(&format!("#define TOTAL_STEPS {}\n\n", project.total_steps));

    let samples_per_step =
        (project.sample_rate_hz as u64 * 60) / (project.bpm as u64 * project.steps_per_beat as u64);
    code.push_str(&format!(
        "#define SAMPLES_PER_STEP {}\n\n",
        samples_per_step
    ));

    code.push_str("typedef struct {\n");
    code.push_str("    uint16_t step;\n");
    code.push_str("    uint8_t note;\n");
    code.push_str("    uint8_t duration_steps;\n");
    code.push_str("    uint8_t velocity;\n");
    code.push_str("} note_event_t;\n\n");

    for track in &project.tracks {
        let safe_name = track.name.replace([' ', '-', '(', ')'], "_").to_lowercase();
        code.push_str(&format!(
            "static const note_event_t track_{}_notes[] = {{\n",
            safe_name
        ));
        for n in &track.notes {
            code.push_str(&format!(
                "    {{ .step = {}, .note = {}, .duration_steps = {}, .velocity = {} }},\n",
                n.step, n.note, n.duration_steps, n.velocity
            ));
        }
        code.push_str("};\n\n");
    }

    code
}
