//! Rust code generation for embedded-audio projects.

use crate::project::{DawProject, TargetMcu};

/// Generates a standalone no_std Rust module containing the song data, hardware timer/DMA setup, and player logic.
pub fn generate_rust_song_code(project: &DawProject) -> String {
    let mut code = String::new();
    code.push_str("//! Auto-generated by embedded-audio DAW studio.\n");
    code.push_str(&format!(
        "//! Target Profile: {:?} | Output Mode: {:?}\n",
        project.hardware_target.target_mcu, project.hardware_target.output_mode
    ));
    code.push_str("//! Architecture: Cortex-M / RISC-V / embedded-audio no_std.\n\n");
    code.push_str("#![no_std]\n\n");
    code.push_str("use embedded_audio::prelude::*;\n");
    code.push_str("use embedded_audio::dsp::BiquadFilter;\n\n");

    code.push_str(&format!(
        "pub const SONG_TITLE: &str = \"{}\";\n",
        project.title
    ));
    code.push_str(&format!("pub const SONG_BPM: u16 = {};\n", project.bpm));
    code.push_str(&format!(
        "pub const SAMPLE_RATE_HZ: u32 = {};\n",
        project.sample_rate_hz
    ));
    code.push_str(&format!(
        "pub const TOTAL_STEPS: u32 = {};\n",
        project.total_steps
    ));
    code.push_str(&format!(
        "pub const STEPS_PER_BEAT: u32 = {};\n",
        project.steps_per_beat
    ));
    code.push_str(&format!(
        "pub const DMA_HALF_BUFFER_SIZE: usize = {};\n\n",
        project.hardware_target.dma_buffer_size
    ));

    let samples_per_step =
        (project.sample_rate_hz as u64 * 60) / (project.bpm as u64 * project.steps_per_beat as u64);
    code.push_str(&format!(
        "pub const SAMPLES_PER_STEP: u32 = {};\n\n",
        samples_per_step
    ));

    // Generate Note Events table
    code.push_str("/// Compact note event (step, note, duration, velocity)\n");
    code.push_str("#[derive(Clone, Copy)]\n");
    code.push_str("pub struct NoteEvent {\n");
    code.push_str("    pub step: u16,\n");
    code.push_str("    pub note: u8,\n");
    code.push_str("    pub duration_steps: u8,\n");
    code.push_str("    pub velocity: u8,\n");
    code.push_str("}\n\n");

    for track in &project.tracks {
        let safe_name = track.name.replace([' ', '-', '(', ')'], "_").to_lowercase();
        code.push_str(&format!(
            "pub const TRACK_{}_NOTES: &[NoteEvent] = &[\n",
            safe_name.to_uppercase()
        ));
        for n in &track.notes {
            code.push_str(&format!(
                "    NoteEvent {{ step: {}, note: {}, duration_steps: {}, velocity: {} }},\n",
                n.step, n.note, n.duration_steps, n.velocity
            ));
        }
        code.push_str("];\n\n");
    }

    // Piezo Acoustic Compensator configuration
    let eq = &project.hardware_target.piezo_eq;
    code.push_str("/// Piezo Transducer DSP Resonance Compensation Filter Parameters\n");
    code.push_str(&format!(
        "pub const PIEZO_EQ_ENABLED: bool = {};\n",
        eq.enabled
    ));
    code.push_str(&format!(
        "pub const PIEZO_RESONANCE_FREQ_HZ: f32 = {:.1};\n",
        eq.resonance_freq_hz
    ));
    code.push_str(&format!(
        "pub const PIEZO_NOTCH_DEPTH_DB: f32 = {:.1};\n",
        eq.notch_depth_db
    ));
    code.push_str(&format!(
        "pub const PWM_CARRIER_FREQ_KHZ: u32 = {};\n\n",
        eq.carrier_freq_khz
    ));

    // Generate Hardware DMA ISR Driver template
    let mcu_isr_name = match project.hardware_target.target_mcu {
        TargetMcu::Stm32U5 => "GPDMA1_Channel0_IRQHandler",
        TargetMcu::Stm32F4 => "DMA1_Stream5_IRQHandler",
        TargetMcu::Rp2040 => "DMA_IRQ_0",
        TargetMcu::Esp32RiscV => "dma_intr_handler",
        TargetMcu::GenericCortexM0 => "DMA1_Channel1_IRQHandler",
    };

    code.push_str(&format!(
        r#"
/// Hardware Autonomous DMA Double-Buffer Playback Handler.
/// Place this in your {} interrupt service routine.
pub struct HardwarePwmAudioDriver {{
    pub sigma_delta: SigmaDelta,
    pub piezo_notch: BiquadFilter,
    pub dma_buffer: [u16; DMA_HALF_BUFFER_SIZE * 2],
}}

impl HardwarePwmAudioDriver {{
    pub fn new() -> Self {{
        Self {{
            sigma_delta: SigmaDelta::new(),
            piezo_notch: BiquadFilter::notch(PIEZO_RESONANCE_FREQ_HZ, 4.0, SAMPLE_RATE_HZ as f32),
            dma_buffer: [0; DMA_HALF_BUFFER_SIZE * 2],
        }}
    }}

    /// Fill active half-buffer during DMA Half-Transfer / Full-Transfer interrupt.
    pub fn fill_half_buffer(&mut self, half_buf: &mut [u16], pcm_samples: &[i8]) {{
        for (out_slot, &pcm) in half_buf.iter_mut().zip(pcm_samples.iter()) {{
            // 1. Apply Piezo Acoustic Resonance Notch Filter
            let filtered = if PIEZO_EQ_ENABLED {{
                self.piezo_notch.process(pcm as f32 / 128.0) * 128.0
            }} else {{
                pcm as f32
            }};

            // 2. Shape through 1-bit Sigma-Delta / PDM Modulator
            let bit = self.sigma_delta.shape(filtered.clamp(-128.0, 127.0) as i8);

            // 3. Map to PWM Timer Compare Register (CCR) value
            *out_slot = if bit > 0 {{ 1000 }} else {{ 0 }};
        }}
    }}
}}

/// Minimal Song Sequencer state machine for embedded audio playback.
pub struct EmbeddedSongPlayer {{
    current_sample: u32,
    current_step: u16,
    is_playing: bool,
}}

impl EmbeddedSongPlayer {{
    pub const fn new() -> Self {{
        Self {{
            current_sample: 0,
            current_step: 0,
            is_playing: false,
        }}
    }}

    pub fn start(&mut self) {{
        self.current_sample = 0;
        self.current_step = 0;
        self.is_playing = true;
    }}

    pub fn stop(&mut self) {{
        self.is_playing = false;
    }}

    /// Advance sequencer by 1 sample. Returns true if a step transition occurred.
    pub fn tick_sample(&mut self) -> Option<u16> {{
        if !self.is_playing {{
            return None;
        }}
        self.current_sample += 1;
        if self.current_sample >= SAMPLES_PER_STEP {{
            self.current_sample = 0;
            let step = self.current_step;
            self.current_step = (self.current_step + 1) % (TOTAL_STEPS as u16);
            Some(step)
        }} else {{
            None
        }}
    }}
}}
"#,
        mcu_isr_name
    ));

    code
}
